# Generated by Django 2.0.7 on 2018-07-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('g_name', models.CharField(max_length=264)),
                ('g_image', models.ImageField(upload_to='')),
                ('g_id', models.CharField(max_length=264, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WebApp.Girl')),
                ('points', models.CharField(max_length=264)),
                ('ranking', models.PositiveIntegerField()),
            ],
        ),
    ]
